# Generated by Django 3.0.8 on 2020-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
