# Generated by Django 3.0.8 on 2020-10-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_auto_20201028_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_reg',
            name='college',
        ),
    ]
