# Generated by Django 3.0.8 on 2020-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_remove_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_reg',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stud_reg',
            name='institute',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
