# Generated by Django 3.0.8 on 2020-11-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_auto_20201102_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=100)),
                ('p_contact', models.CharField(max_length=100)),
                ('p_company', models.CharField(max_length=100)),
                ('p_course', models.CharField(max_length=100, null=True)),
                ('p_sem', models.CharField(max_length=100, null=True)),
                ('p_date', models.CharField(max_length=100, null=True)),
                ('p_time', models.CharField(max_length=100, null=True)),
                ('brochure', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
