# Generated by Django 3.0.8 on 2020-11-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
