# Generated by Django 3.0.8 on 2020-11-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_reg_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_reg',
            name='institute',
        ),
        migrations.AddField(
            model_name='stud_reg',
            name='college_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Reg'),
        ),
    ]
