# Generated by Django 3.0.8 on 2020-11-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_auto_20201119_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
