# Generated by Django 3.0.8 on 2020-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_reg',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
