# Generated by Django 3.0.8 on 2020-11-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_auto_20201119_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
