# Generated by Django 3.0.8 on 2020-11-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_reg_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='p_course',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='p_sem',
        ),
        migrations.DeleteModel(
            name='VolunteerReg',
        ),
    ]
