# Generated by Django 3.0.8 on 2020-11-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_auto_20201119_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Reg')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Placement')),
            ],
        ),
    ]
