# Generated by Django 3.0.8 on 2020-11-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0017_companyreq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyReq',
        ),
    ]
