# Generated by Django 3.0.8 on 2020-11-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0018_delete_companyreq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_reg',
            name='college_id',
        ),
    ]
