# Generated by Django 3.0.8 on 2020-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0020_auto_20201125_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_reg',
            name='adno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
