# Generated by Django 3.0.8 on 2020-11-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0021_stud_reg_adno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Placement')),
            ],
        ),
    ]
