# Generated by Django 3.0.8 on 2020-11-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0023_auto_20201126_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100)),
                ('graduate', models.CharField(max_length=100)),
            ],
        ),
    ]
