# Generated by Django 3.0.8 on 2020-11-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0025_auto_20201128_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Course'),
        ),
    ]
