# Generated by Django 3.0.8 on 2020-11-29 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0026_job_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='course',
        ),
        migrations.AlterField(
            model_name='job',
            name='p_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Course'),
        ),
    ]
