# Generated by Django 3.0.8 on 2020-11-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0027_auto_20201130_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='pg',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='ug',
        ),
    ]
