# Generated by Django 3.0.8 on 2020-12-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0029_job_job_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_status', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Stud_Reg')),
            ],
        ),
    ]
