# Generated by Django 3.0.8 on 2020-12-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0030_jobapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Reg')),
                ('jobapply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Jobapply')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Stud_Reg')),
            ],
        ),
    ]
