# Generated by Django 3.0.8 on 2020-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0031_placedstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('member', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
