# Generated by Django 3.0.8 on 2020-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0034_auto_20201213_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='p_company',
        ),
    ]
