# Generated by Django 3.0.8 on 2021-01-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0035_remove_placement_p_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='ug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
