# Generated by Django 3.0.8 on 2021-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0036_academic_ug'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='batch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
