# Generated by Django 3.0.8 on 2021-01-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0037_academic_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='co_name',
            new_name='name',
        ),
    ]
