# Generated by Django 3.1.1 on 2021-01-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0038_auto_20210105_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='joindate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
